engines:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  fixme:
      enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- data/*
- res/*